logs

diff --git a/soundcard_autoconfigure b/soundcard_autoconfigure
--- a/soundcard_autoconfigure
+++ b/soundcard_autoconfigure
@@ -8,6 +8,19 @@ MK1_CARD_NAME="snd_rpi_proto"  # Mark 1 soundcard
 HDMI_CARD_NAME="vc4-hdmi"       # HDMI soundcard
 HEADPHONES_CARD_NAME="bcm2835"  # Onboard soundcard, not available on rpi5
 
+# Set error handling
+set -euo pipefail
+
+# Function to handle errors
+error_handler() {
+    local line_no=$1
+    local error_code=$2
+    log_message "Error (code: ${error_code}) occurred on line ${line_no}"
+    exit ${error_code}
+}
+
+trap 'error_handler ${LINENO} $?' ERR
+
 
 # Log function to write to a log file
 # Args:
@@ -27,6 +40,7 @@ set_alsa_defaults() {
     echo "defaults.pcm.card $card_number" | sudo tee /etc/asound.conf > /dev/null
     # Set the default control card
     echo "defaults.ctl.card $card_number" | sudo tee -a /etc/asound.conf > /dev/null
+    sudo alsactl restore
     log_message "ALSA default card set to: $card_number"
 }
 
@@ -44,6 +58,7 @@ if echo "$i2c_platform" | grep -q "MARK1"; then
         set_alsa_defaults "$CARD_NUMBER"
     else
         log_message "Error: Could not detect Mark 1 soundcard."
+        exit 1
     fi
 else
     # Check for USB soundcard
